DROP TABLE MEMBER;
CREATE TABLE MEMBER(
    USERNO NUMBER PRIMARY KEY,
    USERID VARCHAR2(15) UNIQUE NOT NULL,
    USERPWD VARCHAR2(20) NOT NULL,
    USERNAME VARCHAR2(15) NOT NULL,
    EMAIL VARCHAR2(30),
    ENROLLDATE DATE DEFAULT SYSDATE NOT NULL
);

DROP SEQUENCE SEQ_USERNO;
CREATE SEQUENCE SEQ_USERNO
NOCACHE;

INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'admin', '1234', '관리자', 'admin@kh.com', '2025/08/16');

INSERT INTO MEMBER
VALUES (SEQ_USERNO.NEXTVAL, 'user01', 'pass01', '홍길동', 'hong@naver.com', SYSDATE);

COMMIT;

CREATE SEQUENCE SEQ_BNO;
SELECT * FROM MEMBER;

DROP TABLE BOARD;
CREATE TABLE BOARD(
    BOARD_NO NUMBER PRIMARY KEY,
    BOARD_TITLE NVARCHAR2(300) NOT NULL,
    BOARD_CONTENT NVARCHAR2(1000) NOT NULL,
    BOARD_WRITER NUMBER REFERENCES MEMBER(USERNO),
    CREATE_DATE DATE DEFAULT SYSDATE,
    DELETE_YN CHAR(1) DEFAULT 'N'
);

INSERT INTO BOARD VALUES


