CREATE TABLE TB_DESSERT(
	DESSERTNO NUMBER NOT NULL,
	DESSERTNAME VARCHAR2(20) NOT NULL UNIQUE,
	CATEGORY VARCHAR2(15) NOT NULL,
	INGREDIENT VARCHAR2(21) NOT NULL,
	CALORIES VARCHAR2(10) NOT NULL,
	ENOLLDATE DATE DEFAULT SYSDATE NOT NULL
);

CREATE SEQUENCE SEQ_DESSERTNO
NOCACHE;

DROP TABLE TB_DESSERT;

INSERT INTO TB_DESSERT VALUES(1, '티라미수', '케이크', '마스카포네치즈', '475kacl', SYSDATE);
INSERT INTO TB_DESSERT VALUES(2, '휘낭시에', '구움과자', '아몬드가루', '353kacl', SYSDATE);
INSERT INTO TB_DESSERT VALUES(3, '소금빵', '빵', '밀가루', '245kcal', SYSDATE);
INSERT INTO TB_DESSERT VALUES(4, '베이글', '빵', '밀가루', '250kcal', SYSDATE);
INSERT INTO TB_DESSERT VALUES(5, '깜빠뉴', '빵', '밀가루', '200kcal', SYSDATE);
INSERT INTO TB_DESSERT VALUES(6, '마카롱', '구움과자', '아몬드가루', '160kcal', SYSDATE);
INSERT INTO TB_DESSERT VALUES(7, '스콘', '구움과자', '밀가루,버터', '353kcal', SYSDATE);
INSERT INTO TB_DESSERT VALUES(8, '쿠키', '구움과자', '밀가루,버터', '228kcal', SYSDATE);

SELECT * FROM TB_DESSERT;

COMMIT;
	

